### ISSUE TITLE
ipbb doesn't play nicely with Python3

### ISSUE THREAD

**Issue by DavidCussans** [ipbus/ipbb#38]
ipbb doesn't install correctly on a machine where Python3 is the default

... also happens with ipbb-0.3.11 release

Work around: use a machine with Python2 as default....

bash-4.4$ git clone git@github.com:ipbus/ipbb.git 
Cloning into 'ipbb'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2227 (delta 0), reused 1 (delta 0), pack-reused 2222
Receiving objects: 100% (2227/2227), 519.18 KiB | 1.41 MiB/s, done.
Resolving deltas: 100% (1512/1512), done.
bash-4.4$ source ipbb/env.sh
Virtualenv /users/phdgc/Downloads/work/ipbb/external/ipbb does not exist.
Setting up a new virtual python environment in /users/phdgc/Downloads/work/ipbb/external/ipbb
Using base prefix '/usr'
New python executable in /users/phdgc/Downloads/work/ipbb/external/ipbb/bin/python3
Also creating executable in /users/phdgc/Downloads/work/ipbb/external/ipbb/bin/python
Installing setuptools, pip, wheel...done.
Upgrading python tools...
Installing ipbb...
Setup completed
Activating ipbb environment
Added /users/phdgc/Downloads/work/ipbb/test/scripts to PATH
Added /users/phdgc/Downloads/work/ipbb/tools/bin to PATH
Traceback (most recent call last):
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/bin/ipbb", line 11, in <module>
    load_entry_point('ipbb', 'console_scripts', 'ipbb')()
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/users/phdgc/Downloads/work/ipbb/ipbb/__init__.py", line 1, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'
Traceback (most recent call last):
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/bin/ipb-prog", line 11, in <module>
    load_entry_point('ipbb', 'console_scripts', 'ipb-prog')()
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/users/phdgc/Downloads/work/ipbb/external/ipbb/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/users/phdgc/Downloads/work/ipbb/ipbb/__init__.py", line 1, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'
ipbb environment successfully loaded

**Comment by alessandrothea** [comment]
Correct. Python 3 is not supported yet.
