### ISSUE TITLE
ipbb v0.5.0 fails to build FLI with Modelsim 10.7c

### ISSUE THREAD

**Issue by DavidCussans** [ipbus/ipbb#47]
Tried to build a simulation project with ipbb v0.5.0 , ipbus v1.4 and Questasim 10.7c

building FLI object file fails:

```(ipbb) -bash-4.2$ ipbb sim fli
/users/phdgc/DUNE/firmware/zcu102/zcu102/ipbb-0.4.3/src/ipbb/cli/__init__.py:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.settings = yaml.load(f)
Traceback (most recent call last):
  File "/users/phdgc/DUNE/firmware/zcu102/zcu102/ipbb-0.4.3/venv/ipbb/bin/ipbb", line 11, in <module>
    load_entry_point('ipbb', 'console_scripts', 'ipbb')()
  File "/users/phdgc/DUNE/firmware/zcu102/zcu102/ipbb-0.4.3/src/ipbb/scripts/builder.py", line 207, in main
    lFirstFrame[3],
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 192: ordinal not in range(128)```

It looks like ipbb needs to be make more robust w.r.t new Questasim versions.

**Comment by alessandrothea** [comment]
David, please enclose console dumps in triple quotes (```), they're hard to read otherwise.

Anyway, by the look of it you're using ipbb `v0.4.3`, not `v0.5.0`.

**Comment by DavidCussans** [comment]
Bother. You are right. I had two directories , one with ipbb v0.4.3 and the other with ipbb v0.5.0 . I must have initialized the wrong one.

Simulation builds and runs with v0.5.0 + Questa 10.7c
